### ISSUE TITLE
[Task] Implement UI integration tests

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat-web#1038]
## Describe the feature
Scaffold some sort of UI integration testing framework to simulate web clicks and web actions. Something like [Selenium Web Driver](https://www.npmjs.com/package/selenium-webdriver).

**Comment by andrewazores** [comment]
This probably fits together well with https://github.com/cryostatio/cryostat-web/issues/1026 . This way the frontend behaviour can be controlled and isolated from any potential bugs that appear in the server. Running the same Selenium-based tests on a live instance could be used as a form of contract testing to ensure that the real backend and the mock API both behave the same way, assuming that they are both perfectly repeatable and reliable. In practice the real backend may not always be since it also needs to talk to target applications over the network, so there can be a lot of points of failure that could confuse our reading of frontend test failures.

**Comment by maxcao13** [comment]
That's true, and it doesn't require the entire startup of the backend and the deployment and all that which takes time, and should only be testing UI functionality.

**Comment by andrewazores** [comment]
I've also seen far too often that the GitHub Actions CI runner just completely fails to start the Cryostat container in the backend's itest runs, for whatever reason. It just gives me the process exit code (`124` IIRC), but I never tracked down what it actually means for podman/libpod/whatever to exit with that status. That kind of failure would also be very annoying to run into during frontend tests.
