### ISSUE TITLE
Re-uploading a saved recording does not modify the second file name

### ISSUE THREAD

**Issue by jan-law** [cryostatio/cryostat-web#398]
Behaviour occurs on the `main` branch as well as #397 

To reproduce bug:
1. Create a recording
2. Archive the recording
3. Download the recording you just archived
4. Re-upload the downloaded recording
5. The second file name is the same as the first one. Any "Delete" or "Edit Metadata" actions affect both recordings.

![image](https://user-images.githubusercontent.com/84587295/159542086-56364e5e-61fd-44f6-a4ed-42d6df6f9a81.png)

This alternative code path works fine - I'm assuming this is the intended behaviour:
Click the 'plus' icon and upload the same recording file twice, the second recording gets a number appended to it.
![image](https://user-images.githubusercontent.com/84587295/159541813-6a832c11-afb8-4f37-9ef5-ded548a6a592.png)

**Comment by andrewazores** [comment]
This happens because re-uploading a recording into the archives puts it into a general, "unlabelled" archives subdirectory, rather than the one belonging to the selected target. If you repeat this procedure in #397, I think the per-target archives on the Recordings page should behave as expected, since it also no longer allows for recordings to be uploaded to the general "unlabelled" subdirectory from there, and the query it performs should only return results from the correct archive subdirectory as well. The new Archives page can still display these apparent duplicates however.

**Comment by andrewazores** [comment]
Since #397 is merged this bug should not appear in the Recordings page archives tab, but it will still affect the new All Archives view (until #431).

**Comment by andrewazores** [comment]
@dfitzmau @kucollin can we document this as a Known Issue for 2.1.0? It is a small display-only bug that affects the new Archives view.

**Comment by dfitzmau** [comment]
Hi @andrewazores . Yes, we can document this. Just to confirm the issue still exists? I'm asking as two PRs exist related to this issue.

#437
#398

**Comment by andrewazores** [comment]
@dfitzmau yes, the issue still exists. Those PRs have not been merged yet, so there won't be a fix in a product version until 2.2.0 later this year.
