### ISSUE TITLE
Target-specific archives table displays archived recording for different target after notification

### ISSUE THREAD

**Issue by jan-law** [cryostatio/cryostat-web#420]
To reproduce:
1. Recordings > Select cryostat container cryostat:9091 and go to Archived Recordings table
2. Open a second web client tab > Recordings > Select quarkus container on cryostat:9096
3. On second web client, start a recording on cryostat:9096
4. Archive the recording on cryostat:9096
5. Open the first web client tab. The archived recording from cryostat:9096 appears on the table, even though the table should only show the archived recordings for cryostat:9091. Refreshing the page shows the correct list of archived recordings.

**Comment by andrewazores** [comment]
Nice find. It sounds like the table is listening for notifications to update its state, but it isn't checking that the `target` field of the notification matches the currently selected target. The table or its parent view must already have a reference to the frontend `target` service that can tell it what the currently selected target is, so the fix is to just filter the incoming notifications for only those that match the currently selected target.

**Comment by andrewazores** [comment]
@jan-law do you want to take a stab at this one yourself? This should go into 2.1.
