### ISSUE TITLE
[Task] Killing and running pod in quick succession unsyncs GET /targets and ServiceContext targets

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat-web#493]
To recreate

1. run `smoketest.sh` 
2. run `podman ps --format "{{.Pod}} || {{.ID}} || {{.Names}}"` to find the container id of a sample app (e.g. for vertx.fib-demo-1)
3. run `podman kill $ID_OF_APP && podman run         --name vertx-fib-demo-1         --env HTTP_PORT=8081         --env JMX_PORT=9093         --pod cryostat-pod         --rm -d quay.io/andrewazores/vertx-fib-demo:0.7.0`
4. A target FOUND notification should show with the 'new' target (however there is no LOST target notification for the old target)

    _**_4(a). If you refresh targets between steps 4 and 5, for a few seconds, the dropdown will show 2 targets with the same name and connect-url._**_

5. Wait a several seconds without refreshing, and finally a new LOST target notification shows, however it removes the target from the dropdown selection

Pressing the refresh target does bring it back since the button queries /targets.

**Comment by andrewazores** [comment]
This is happening because the discovery mechanism in use is [JDP](https://docs.oracle.com/javase/10/management/java-discovery-protocol.htm#JSMGM-GUID-4FE44ECD-E1A7-42CE-9AD8-A2E582C55C43). We default to that when we don't detect a more platform-specific mechanism (ex. `KubeApiPlatformClient`), so in `smoketest.sh` that's what you are using. JDP works by multicasting network packets to broadcast the target JVM's presence. These broadcasts happen on an interval, and I think there is also some logic in the packet listener to not count a JVM as lost until a few expected broadcasts are missed (to account for potential dropped packets?):

https://github.com/cryostatio/cryostat-core/blob/main/src/main/java/io/cryostat/core/net/discovery/JvmDiscoveryClient.java
https://github.com/cryostatio/cryostat-core/blob/main/src/main/java/org/openjdk/jmc/jdp/client/JDPClient.java

Unfortunately I think this bug is just a natural consequence of JDP and any other discovery mechanism that has this broadcast delay built into it. If it takes longer to register that a target has disappeared than the time for the target to reappear then things will get funny.

To properly fix this we need a better way to identify targets. Right now we just use the JMX service URL and perhaps the alias and assume that that uniquely identifies a target JVM. So, if an instance goes away and is immediately replaced, we run into the behaviour you describe.

https://github.com/cryostatio/cryostat/pull/971

If/when we start computing unique hash IDs for targets then we can/should include that information in the `ServiceRef` structure we use for tracking them, and we should also emit that in the WebSocket notifications for target discovery events. The web-client should handle this hash ID as well and use that to add/remove targets from the UI. There may end up being a brief overlapping period where two targets are visible with identical connection URLs, and both will also be "known" to Cryostat in that interim period (and so may be subject to things like Automated Rules processing), so maybe we need to also do some pruning logic on the backend side. If we discover a new target that has a different hash ID but the same connection URL as a previous target then maybe we should proactively remove the previous target definition?

**Comment by maxcao13** [comment]
That's very interesting about JDPs' discovery mechanism, I didn't know that,

> If we discover a new target that has a different hash ID but the same connection URL as a previous target then maybe we should proactively remove the previous target definition?

Right, I was thinking that too


Gotcha, it makes sense to me now. Once https://github.com/cryostatio/cryostat/pull/971 gets merged, I will look into implementing this logic then, as well as start doing some other issues that depend on it, e.g. [cryostat/972](https://github.com/cryostatio/cryostat/issues/972)
