### ISSUE TITLE
[Task] Add progress spinner to action buttons

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#597]
Related to https://github.com/cryostatio/cryostat/pull/1089
Related to #592

Creating a custom target definition results in Cryostat trying to connect to that target to determine its unique JVM ID. This takes some time and may time out after a few seconds if the definition used a JMX URL that points to nothing, for example. The custom target creation UI should be updated to handle this more nicely - the text boxes should be disabled and a spinner displayed overtop when a request is in progress. On success the modal should close, on failure the spinner should disappear and the text boxes re-enable but the modal remain.

**Comment by tthvo** [comment]
It was pretty tricky to add the spinner overlay only on the creation modal since Patternfly does not have a component for this purpose (maybe not the recommended design?) and do it manually requires dynamically check for modal boundary. 

Right now, i could add an overlay (`Backdrop`) for the entire screen.

![Screenshot from 2022-11-04 21-11-55](https://user-images.githubusercontent.com/68053619/200094729-37cf4e53-da0d-4cb8-8496-be1a9217c5fb.png)

What do you think?

**Comment by andrewazores** [comment]
I think that looks OK, but digging a little deeper in PF docs I think what we should do is like this:

https://www.patternfly.org/v4/components/button/html-demos/#progress-button---loading

ie. there should be a spinner within the `Create` button itself. I think disabling the text fields at the same time still makes sense too.

**Comment by andrewazores** [comment]
There are probably other places we can apply this too, not just for custom target creation. Defining a rule, adding credentials to keyring, starting a recording, etc. would all make sense.

**Comment by tthvo** [comment]
Right that makes sense! I will follow that patternfly styles and add progress indicators :D
