### ISSUE TITLE
[Task] Add support for UI localization

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat-web#625]
https://www.npmjs.com/package/@shopify/react-i18n

This or another similar library should help. UI strings should be provided by loadable documents rather than hardcoded into components.

Error messages from the backend will still end up in English, but those should either be dealt with separately, or localized strings used instead by the frontend by looking up ex. specific HTTP status codes in particular contexts.

**Comment by maxcao13** [comment]
Doing a bit of research, it and looking at different i18n frameworks for React from this list https://github.com/jpomykala/awesome-i18n, I think narrowing it down from [react-i18next](https://react.i18next.com/) and formatjs's [react-intl](https://formatjs.io/docs/react-intl/), I think I will try react-i18next because it has a smaller bundle size, but both packages seem to do the same thing, react-intl just seems to be a bit more popular on GitHub with more stars.
