### ISSUE TITLE
[Bug] Dashbard should hide cards with unmatching feature level

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-web#840]
## Current Behavior:

Noticed this today that cards belong to lower `FeatureLevel` still persist if switching from lower to higher feature level.

## Expected Behavior:

Dashboard only shows cards matching current feature level.

## Screenshots

Notice how console is in `PRODUCTION` mode but a None card is still shown.

![Screenshot from 2023-01-31 12-43-05](https://user-images.githubusercontent.com/68053619/215840800-6de52ded-ffc3-4586-a0c6-42799eb91946.png)

## Steps To Reproduce:
1. Go into DEVELOPMENT mode
2. Create any dev card
3. Switch back to PRODUCTION/BETA
4. Those cards still persist in dashboard.

**Comment by tthvo** [comment]
Fixes seem to complicate reordering and resizing. Any thoughts? I guess it only affect releases that has BETA cards.

**Comment by andrewazores** [comment]
I don't think we would want to make any permanent modifications to the user's dashboard config when they change feature levels. Since the feature level is included in the card configuration properties, maybe the whole card component can just be wrapped in a feature flag at that level. This way it can still be included in the persisted serialized layout, but it will only be rendered if the correct feature level is selected. Or even simpler, maybe there should just be a feature level badge on the card headers similar to what is displayed on the application masthead bar. This way it's explicit to the user if the cards they are using are part of the beta feature flag level and they can decide on their own what to do with that.

**Comment by maxcao13** [comment]
I think this issue has been resolved, thoughts?
