### ISSUE TITLE
[Request] Notify users about available quickstarts if any

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-web#970]
## Describe the feature

We should add an initial banner to tell new users that there are available quickstarts that they can go over. Content [1] like:

```
Welcome to Cryostat! To get started, please visit out quickstarts!
```

## Any other information?

There is a `HintBanner` component already declared and styled. We can move it out of topology and use it globally.

https://github.com/cryostatio/cryostat-web/blob/4251e821d7420b0e224ff45f594ed03da9204ad0/src/app/Topology/Shared/HintBanner.tsx

**Example:**

Note: This example was specific for topology but the hint content should be generic as above [1].

![222600846-909200e0-3eb8-4367-9244-0479d5dc6129](https://user-images.githubusercontent.com/3787464/222600846-909200e0-3eb8-4367-9244-0479d5dc6129.png)

**Comment by andrewazores** [comment]
Would this also be solved by informing the user about the Quickstarts in the guided tour, and then making sure the guided tour is displayed to users if it is their first time opening the web-client? I guess whatever record we place into LocalStorage to detect that case should be versioned so that on the next version upgrade the guided tour is displayed again.

**Comment by tthvo** [comment]
Yehh this seems to be a better idea than the banner then. I will update #971.
